print("root@spaceos")
print("------------")
print("OS: SpaceOS Python3 OS v2")
print("Host: Space LPU 1")
print("Kernel: Python3-discord.gg/hetzner")
print("Shell: SpaceSH")
print("Terminal: Python3")
print("CPU: Space LPU (64) @ 4.900GHz")
print("GPU: Space LPU 4090")
print("Memory: 128G")
